---
title: "Tarea 5-Introducción a la Representación Gráfica"
author: "Yimmy Eman"
date: '2022-06-29'
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Pregunta 1

```{r}
f <- function(x){x^2-3*x+30}
curve(f, -15, 15, 
      main = "Una parábola", 
      xlab = expression(X), 
      ylab = expression(y = x^2-3*x+30)
      )
```

## Pregunta 2

Incorrecto, para que la variable $x \in [-15, 15]$ se debe definir de la siguiente forma:
```{r}
I <- c(-15:15)
plot(I, f(I), col = "blue", type = "l",
      main = "Una parábola", 
      xlab = expression(X), 
      ylab = expression(y = x^2-3*x+30))
```

## Pregunta 3

```{r}
g <- function(x){5 * 2^x}

curve(g,-1,25, log = "y", xlab = "", ylab = expression(y = 5 %.% 2^x))
```

## Pregunta 4

```{r}

curve(3*x,-10,20,
      xlab = "",
      ylab = "",
      col = "blue", 
      main = "Dos rectas",
      sub = "Dos rectas con pendiente opuesto"
      )
abline(0,-3, col = "green")
legend(13, 10, 
       legend =c("3x","-3x"), 
       lty =c(1, 1), 
       col =c("blue", "green"))
```
## Pregunta 5

```{r}
curve(3*x,-10,20,
      xlab = "",
      ylab = "",
      col = "blue", 
      main = "Dos rectas",
      sub = "Dos rectas con pendiente opuesto",
      )
abline(0,-3, col = "green")
abline(h = 0, col = "red", lwd = 5)
legend(13, 10, 
       legend =c("3x","-3x"), 
       lty =c(1, 1), 
       col =c("blue", "green"))
```
## Pregunta 6

```{r}
curve(3*x,-10,20,
      xlab = "",
      ylab = "",
      col = "blue", 
      main = "Dos rectas",
      sub = "Dos rectas con pendiente opuesto",
      )
curve(-3*x, col = "green", add = T)
abline(h = 0, col = "red", lwd = 5)
abline(7,2, col = "blue", lwd = 2)
legend(13, 10, 
       legend =c("3x","-3x"), 
       lty =c(1, 1), 
       col =c("blue", "green"))
```

